# Generated by Django 3.2.9 on 2021-12-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_auto_20211208_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('img', models.ImageField(upload_to='picture')),
                ('cap', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
